# Generated by Django 3.1.2 on 2020-10-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convertapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='uploaded_at',
            new_name='uploadedAt',
        ),
    ]
